### ISSUE TITLE
New release (v0.1.3)

### ISSUE THREAD

**Issue by GenevieveBuckley** [12rambau/pytest-copie#57]
**Is your feature request related to a problem? Please describe.**
I am using pytest-copie in a projec and our CI jobs are failing because of errors happening in the test teardown process ([details here](https://github.com/napari/napari-plugin-template/pull/1#issuecomment-1788572419)).

**Describe the solution you'd like**
I would like there to be a new release of pytest-copie. 
Then we could pin the version in our CI environment, and avoid the failing tests.

Recent PRs https://github.com/12rambau/pytest-copie/pull/51 and https://github.com/12rambau/pytest-copie/pull/56 are very useful, and I think it would be helpful to make them widely available.

**Describe alternatives you've considered**
We can also install pytest-copie on our CI from the main branch on github, eg: `pip install git+https://github.com/12rambau/pytest-copie.git`. That would work well, and then later on we could pin to the next release whenever it becomes available.

**Comment by 12rambau** [comment]
I would like to close your last 2 PRs before making a new release but it's in the pipe no worries.

**Comment by 12rambau** [comment]
published by https://github.com/12rambau/pytest-copie/actions/runs/6850644081/job/18625216650

I'll release in a follow-up patch the documentation updates.
